//! Regenerate the TypeScript IPC bindings and the file-type table without
//! launching the app:
//!
//! ```sh
//! cargo run -p novalis-desktop --example gen_bindings
//! ```
//!
//! Both are also regenerated by every debug build (see `lib::run`), so
//! `just dev` cannot run against a stale file. `just check` and CI run this
//! example and refuse a `bindings.ts` or `fileTypes.generated.ts` that
//! differs from the committed one (PLAN.md §11.2).

fn main() {
    novalis_desktop_lib::export_bindings();
    println!("exported apps/desktop/ui/src/ipc/bindings.ts and apps/desktop/ui/src/lib/fileTypes.generated.ts");
}
