// This file has been generated from the desktop crate's `file_types.rs`. Do not edit it manually;
// regenerate with `cargo run -p novalis-desktop --example gen_bindings` (PLAN.md §7.3, ADR-0022).

export type FileKind = "note" | "text" | "view";

/** Lower-case extension → what the app does with the file. */
export const EXTENSION_KINDS: Readonly<Record<string, FileKind>> = {
  "md": "note",
  "markdown": "text",
  "txt": "text",
  "text": "text",
  "rst": "text",
  "adoc": "text",
  "org": "text",
  "textile": "text",
  "mkd": "text",
  "mdx": "text",
  "rmd": "text",
  "qmd": "text",
  "srt": "text",
  "vtt": "text",
  "tex": "text",
  "ltx": "text",
  "json": "text",
  "json5": "text",
  "jsonc": "text",
  "yaml": "text",
  "yml": "text",
  "toml": "text",
  "xml": "text",
  "xsl": "text",
  "xsd": "text",
  "plist": "text",
  "svg": "text",
  "csv": "text",
  "tsv": "text",
  "log": "text",
  "diff": "text",
  "patch": "text",
  "bib": "text",
  "ini": "text",
  "properties": "text",
  "cfg": "text",
  "env": "text",
  "conf": "text",
  "html": "text",
  "htm": "text",
  "css": "text",
  "scss": "text",
  "sass": "text",
  "less": "text",
  "js": "text",
  "mjs": "text",
  "cjs": "text",
  "jsx": "text",
  "ts": "text",
  "mts": "text",
  "cts": "text",
  "tsx": "text",
  "vue": "text",
  "py": "text",
  "rb": "text",
  "pl": "text",
  "pm": "text",
  "php": "text",
  "lua": "text",
  "tcl": "text",
  "ps1": "text",
  "sh": "text",
  "bash": "text",
  "zsh": "text",
  "c": "text",
  "h": "text",
  "cpp": "text",
  "cc": "text",
  "cxx": "text",
  "hpp": "text",
  "hh": "text",
  "hxx": "text",
  "rs": "text",
  "go": "text",
  "swift": "text",
  "java": "text",
  "kt": "text",
  "kts": "text",
  "scala": "text",
  "cs": "text",
  "groovy": "text",
  "gradle": "text",
  "dart": "text",
  "hs": "text",
  "ml": "text",
  "mli": "text",
  "elm": "text",
  "erl": "text",
  "clj": "text",
  "cljs": "text",
  "edn": "text",
  "lisp": "text",
  "el": "text",
  "scm": "text",
  "r": "text",
  "jl": "text",
  "sql": "text",
  "proto": "text",
  "dockerfile": "text",
  "cmake": "text",
  "mk": "text",
  "pdf": "view",
  "png": "view",
  "jpg": "view",
  "jpeg": "view",
  "gif": "view",
  "webp": "view",
};

/** Whole file name → kind, for files that have no extension worth the name. */
export const NAME_KINDS: Readonly<Record<string, FileKind>> = {
  "Gemfile": "text",
  "Rakefile": "text",
  "Jenkinsfile": "text",
  "Dockerfile": "text",
  "Containerfile": "text",
  "Makefile": "text",
  "GNUmakefile": "text",
  "makefile": "text",
  "Justfile": "text",
  "justfile": "text",
  "LICENSE": "text",
  "README": "text",
  "CHANGELOG": "text",
  "CONTRIBUTING": "text",
  "AUTHORS": "text",
  "NOTICE": "text",
  "COPYING": "text",
  "VERSION": "text",
  "TODO": "text",
  "CODEOWNERS": "text",
};

/** Regex source over the file name → kind, tried after the two maps. */
export const PATTERN_KINDS: Readonly<Record<string, FileKind>> = {
  "^Dockerfile\\..+$": "text",
};
