// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Everything the first paint needs, in one call (PLAN.md §2.3 rule 8).
	 *  The tree is the root listing only; sub-folders are fetched by `list_dir`
	 *  when they open, so first paint never waits for a walk (rule 1).
	 */
	bootstrap: () => typedError<BootstrapDto, IpcError>(__TAURI_INVOKE("bootstrap")),
	/**  The one dialog the app opens. Returns `None` when the user cancels. */
	openVaultDialog: () => typedError<string | null, IpcError>(__TAURI_INVOKE("open_vault_dialog")),
	openVault: (path: string) => typedError<VaultOpenDto, IpcError>(__TAURI_INVOKE("open_vault", { path })),
	listDir: (path: string) => typedError<EntryDto[], IpcError>(__TAURI_INVOKE("list_dir", { path })),
	/**
	 *  Every regular file in the vault, vault-relative and sorted — not only
	 *  notes (ADR-0022): quick-open lists every file the tree would, and the
	 *  `[[`-completion source keeps the `.md` among them. The UI applies the
	 *  file-type table; the shell hands over the walk, because the table's name
	 *  patterns are the UI's to run. The tree only knows the folders the user
	 *  has opened. `walk_files` runs under the materialize-off guard and stats
	 *  only, so a 10k-note cloud vault costs no downloads.
	 */
	listFiles: () => typedError<string[], IpcError>(__TAURI_INVOKE("list_files")),
	readFile: (path: string) => typedError<FileDto, IpcError>(__TAURI_INVOKE("read_file", { path })),
	/**
	 *  Read a file the viewer shows as it is — a PDF or an image (ADR-0015).
	 *  Same explicit-open rule as `read_file`: a cloud-only file is downloaded
	 *  here on purpose. Anything above [`HUGE_FILE_BYTES`] is refused rather
	 *  than sent through the IPC as one string.
	 */
	readBlob: (path: string) => typedError<BlobDto, IpcError>(__TAURI_INVOKE("read_blob", { path })),
	/**
	 *  Read inside a container the viewer shows one part at a time — an EPUB or
	 *  a CBZ (ADR-0023). With `entries` empty this is the container's table of
	 *  contents; otherwise it is those entries' bytes, all of them in this one
	 *  call, because a chapter and the twenty images it references are one user
	 *  action and rule 8 gives it one round trip, not twenty-one.
	 * 
	 *  Same explicit-open rule as `read_blob`: a cloud-only book is downloaded
	 *  here on purpose. The core caps each entry; this caps what one call may
	 *  put through the IPC as base64, for the same reason `read_blob` does.
	 */
	readPacked: (path: string, entries: string[]) => typedError<PackedDto, IpcError>(__TAURI_INVOKE("read_packed", { path, entries })),
	/**
	 *  Write an image or PDF the user pasted or dropped into a note (ADR-0017,
	 *  ADR-0041) or dropped on the tree from the Finder, under
	 *  `folder/name`, never over an existing file (`RENAME_EXCL`), parents
	 *  created. Only the §7.3 image types, and nothing above [`HUGE_FILE_BYTES`].
	 */
	writeBlob: (folder: string, name: string, base64: string) => typedError<EntryDto, IpcError>(__TAURI_INVOKE("write_blob", { folder, name, base64 })),
	/**
	 *  The read-only preview of a note (ADR-0020): the text the editor holds,
	 *  frontmatter and all, as an HTML fragment the preview pane inserts as it
	 *  is (raw HTML in the note comes back as text — `notes::render`).
	 */
	renderMarkdown: (text: string) => typedError<string, IpcError>(__TAURI_INVOKE("render_markdown", { text })),
	/**
	 *  Save. `expected` is the precondition captured when the buffer was loaded or
	 *  last written; a mismatch is a `conflict` and the target is left untouched,
	 *  so the UI can write the buffer to a conflict copy (§5.3 step 3).
	 */
	writeFile: (path: string, text: string, expected: {
	mtimeNs: string,
	size: string,
	hash: string,
} | null) => typedError<PreconditionDto, IpcError>(__TAURI_INVOKE("write_file", { path, text, expected })),
	/**
	 *  Write the buffer to `<name> (conflict <host> <YYYY-MM-DD HHMM>).<ext>` next
	 *  to the target and return the new vault-relative path. Never clobbers
	 *  (§5.3 step 3).
	 */
	writeConflictCopy: (path: string, text: string) => typedError<string, IpcError>(__TAURI_INVOKE("write_conflict_copy", { path, text })),
	/**
	 *  Create an empty file in the vault: a note (`.md`) or, when the typed name
	 *  carries a §7.3 extension, that file type (ADR-0014). Both go through the
	 *  same guards as `vault_note_rel` minus the `.md` requirement; nothing hidden
	 *  and nothing outside the vault is ever created.
	 */
	createNote: (folder: string, name: string) => typedError<EntryDto, IpcError>(__TAURI_INVOKE("create_note", { folder, name })),
	createFolder: (folder: string, name: string) => typedError<EntryDto, IpcError>(__TAURI_INVOKE("create_folder", { folder, name })),
	/**
	 *  Rename or move, then rewrite the links that pointed at the old name.
	 * 
	 *  `vault::fs::rename` handles the case-only and normalization-only twins and
	 *  never clobbers; `relink_many` runs under the materialize-off guard and
	 *  writes each note under its read-time precondition, reporting what it had to
	 *  skip (§5.3 step 6).
	 */
	rename: (from: string, to: string) => typedError<RenameResultDto, IpcError>(__TAURI_INVOKE("rename", { from, to })),
	/**
	 *  Move to the Trash with `NsFileManager` (no prompt, no entitlement — the
	 *  §4.5 decision). A cloud-only file is refused rather than materialized.
	 */
	trash: (path: string) => typedError<null, IpcError>(__TAURI_INVOKE("trash", { path })),
	/**
	 *  Hand something to macOS's own opener, `/usr/bin/open` — no plugin, and
	 *  novalis itself opens no connection (docs/PRIVACY.md): `reveal` shows a
	 *  vault file selected in the Finder (ADR-0021), `default` opens it in the
	 *  app macOS picks for its type (ADR-0043), `url` opens a web or mail link
	 *  in the default browser or mail app (ADR-0044). A path is checked against
	 *  the vault like every other and is absolute, so it can never be read as an
	 *  option; a URL must pass [`external_url`]. macOS only, as the app is (PLAN.md §4.5); the Linux build answers
	 *  with an error.
	 */
	systemOpen: (target: SystemOpenDto) => typedError<null, IpcError>(__TAURI_INVOKE("system_open", { target })),
	/**
	 *  A native context menu popped at the pointer (ADR-0021, ADR-0032). The
	 *  tree's entries are File menu items with the File menu's ids, so a click
	 *  arrives in the UI as the same `MenuAction` a menu-bar click does and runs
	 *  the same command against the row the UI selected before asking; a board
	 *  row gets "Show in Finder" only. A card's entries act on the card the UI
	 *  remembered before asking.
	 */
	contextMenu: (target: ContextMenuDto) => typedError<null, IpcError>(__TAURI_INVOKE("context_menu", { target })),
	/**
	 *  Vault-wide search, streamed over a channel. A newer search supersedes an
	 *  older one: the running scan sees the generation change and stops, so there
	 *  is no cancel command and no way to leak a worker.
	 */
	search: (query: SearchQueryDto, onEvent: Channel<SearchEventDto>) => typedError<SearchReportDto, IpcError>(__TAURI_INVOKE("search", { query, onEvent })),
	/**
	 *  Every tag in the vault with its note count, most used first.
	 * 
	 *  Reads the cache on its own short-lived connection rather than through the
	 *  actor: the database is WAL and the actor's scan does its file reads before
	 *  it opens a write transaction, so a reader never waits on a scan.
	 */
	tags: () => typedError<TagListDto, IpcError>(__TAURI_INVOKE("tags")),
	/**  The notes and cards that link to `path` (§4.4, approved for v1). */
	backlinks: (path: string) => typedError<BacklinksDto, IpcError>(__TAURI_INVOKE("backlinks", { path })),
	boardList: () => typedError<BoardRefDto[], IpcError>(__TAURI_INVOKE("board_list")),
	/**
	 *  A board and its cards in one read. Tombstoned cards are dropped here;
	 *  cloud-only card files are reported, never read (§8.2). The first read of a
	 *  board after the vault was opened also resolves its `board.json` and card
	 *  conflicts (§8.4) and says so in `resolved_columns` and
	 *  `resolved_conflicts`; only that read writes, every later one carries
	 *  false and 0.
	 */
	boardRead: (slug: string) => typedError<BoardDto, IpcError>(__TAURI_INVOKE("board_read", { slug })),
	/**
	 *  Create `boards/<slug>/board.json`. The board starts without columns: column
	 *  names are user text and the UI owns the catalog, so the shell never invents
	 *  one.
	 */
	boardCreate: (slug: string, name: string) => typedError<BoardRefDto, IpcError>(__TAURI_INVOKE("board_create", { slug, name })),
	/**
	 *  The two configurable things about a board: its name and its column list
	 *  (§8.5). Columns go through `set_columns`, which re-reads and replays on a
	 *  conflict, so two devices reordering columns never lose one.
	 */
	boardWrite: (slug: string, name: string | null, columns: ColumnDto[] | null, place: { kind: "first" } | { kind: "last" } | { kind: "after"; id: string } | null) => typedError<BoardDto, IpcError>(__TAURI_INVOKE("board_write", { slug, name, columns, place })),
	/**
	 *  The one write the board pane makes. Every variant is a single replayable
	 *  field change, which is why a conflicting board never raises a banner
	 *  (§5.3 step 5).
	 */
	cardWrite: (slug: string, op: CardOpDto) => typedError<CardDto, IpcError>(__TAURI_INVOKE("card_write", { slug, op })),
	/**
	 *  Change one or more of the four settings (PLAN.md §4.1). Writes
	 *  `settings.json` atomically and rebuilds the native menu so its check marks
	 *  and the Language/Appearance submenus match.
	 */
	settingsSet: (patch: SettingsPatchDto) => typedError<SettingsDto, IpcError>(__TAURI_INVOKE("settings_set", { patch })),
	/**
	 *  Persist the disposable half of the UI state (open tabs, sidebar, board).
	 *  It lives in `<app-data>/state.json` and is deliberately not documented in
	 *  `docs/SETTINGS.md` (PLAN.md §4.1).
	 */
	stateSave: (uiState: UiStateDto) => typedError<null, IpcError>(__TAURI_INVOKE("state_save", { uiState })),
};

/** Events */
export const events = {
	cacheUpdated: makeEvent<CacheUpdated>("cache-updated"),
	fsBatch: makeEvent<FsBatch>("fs-batch"),
	menuAction: makeEvent<MenuAction>("menu-action"),
	openRequested: makeEvent<OpenRequested>("open-requested"),
};

/* Types */
export type AppearanceDto = "system" | "light" | "dark";

/**
 *  A card whose `notes[]` references the open note (§4.4: the backlinks list
 *  shows cards linking here, not only notes).
 */
export type BacklinkCardDto = {
	board: string,
	boardName: string,
	id: string,
	title: string,
};

export type BacklinkDto = {
	path: string,
	title: string,
	/**  The line the link sits on, 1-based. */
	line: number,
	/**
	 *  That line as the vault search would show it, so two links from the
	 *  same note can be told apart; empty when the note could not be read.
	 */
	snippet: string,
};

export type BacklinksDto = {
	notes: BacklinkDto[],
	/**
	 *  Cards come from the board files, not the cache: a card is not a note
	 *  and is never indexed, so this half works even while `indexed` is false.
	 */
	cards: BacklinkCardDto[],
	/**  See [`TagListDto::indexed`]. Applies to `notes` only. */
	indexed: boolean,
};

/**
 *  A file the viewer shows as it is (PDF, image — ADR-0015). Base64 because
 *  the typed IPC has no raw-bytes return; the viewer turns it into a `blob:`
 *  URL and never keeps it. Capped at [`HUGE_FILE_BYTES`].
 */
export type BlobDto = {
	path: string,
	/**  Bytes, base64 (standard alphabet, padded). */
	base64: string,
	/**  Byte count as a decimal string (see `EntryDto`). */
	size: string,
};

/**  A board with its cards, in one read. Tombstoned cards are not sent. */
export type BoardDto = {
	slug: string,
	name: string,
	columns: ColumnDto[],
	cards: CardDto[],
	/**  Card files that are online only and were therefore never read. */
	cloudOnly: string[],
	/**
	 *  Cards whose `column` is not in `columns` any more; the UI shows them in
	 *  the first column with a marker (`board.columnMissing`).
	 */
	orphanCards: string[],
	/**
	 *  Card files that could not be used: a name that is not a bare ULID
	 *  (a vendor conflict copy looks like that) or a body that does not parse.
	 *  They used to be dropped in silence, so a card vanished with no reason.
	 */
	unreadable: string[],
	/**
	 *  Cards that had conflicting siblings and were resolved by this read
	 *  (§8.4): the newer card won and the older is under `conflicts/`. Only
	 *  the first read of a board after the vault was opened resolves, so this
	 *  is non-zero at most once per board and the UI keeps it until dismissed
	 *  (`board.conflictNotice`); every later read carries 0.
	 */
	resolvedConflicts: number,
	/**
	 *  True when that same first read found conflict copies of `board.json`
	 *  and resolved them (§8.4, "same rule"): the newer document won, the
	 *  columns of both were unioned, the older copy is under `conflicts/`.
	 *  Kept by the UI until dismissed (`board.columnsMerged`).
	 */
	resolvedColumns: boolean,
	/**
	 *  Set when that first read tried to resolve and could not. The board is
	 *  still returned — a board that cannot be tidied is still a board — and
	 *  the UI reports the error like any failed command.
	 */
	resolveError: IpcError | null,
};

export type BoardRefDto = {
	slug: string,
	name: string,
	/**
	 *  The board's place among the boards (ADR-0019); `None` until dragged.
	 *  The list arrives in display order either way.
	 */
	order: string | null,
};

export type BootstrapDto = {
	settings: SettingsDto,
	vault: VaultDto | null,
	/**
	 *  The vault root's children. Sub-folders are fetched lazily by `list_dir`,
	 *  so the first paint never waits for a full walk (PLAN.md §2.3 rule 1).
	 */
	tree: EntryDto[],
	lastOpen: UiStateDto,
	/**
	 *  The resolved UI language (`de` or `en`) — `language: system` is
	 *  resolved here so the UI and the native menu agree.
	 */
	locale: string,
	/**
	 *  The value of `NOVALIS_PERF`, when set: the UI runs its keystroke
	 *  probe (`1`) or a self-typing burst (`type:<n>`) and prints the
	 *  PLAN.md §11.3 numbers to the console (`ui/src/lib/perf.ts`).
	 */
	perf: string | null,
	/**
	 *  Files and `novalis://` links macOS handed to the app before the page
	 *  was up — a launch by Open With or a Dock drop (ADR-0045).
	 */
	pendingOpen: OpenRequestDto[],
};

/**
 *  Emitted after every completed scan, so the panels that read the cache
 *  refetch when there is something new rather than on a timer (§2.3 rule 12
 *  forbids polling).
 */
export type CacheUpdated = {
	/**
	 *  False when the cache could not be opened or scanned; the tag filter and
	 *  the backlinks list then say so instead of showing an empty result.
	 */
	indexed: boolean,
};

export type CardDto = {
	id: string,
	title: string,
	column: string,
	order: string,
	notes: string[],
	created: string,
	updated: string,
	/**  Markdown text under the title (ADR-0013); `None` when the card has none. */
	description: string | null,
	/**
	 *  The description rendered by the preview's renderer (ADR-0033), raw
	 *  HTML in it escaped; `None` with the description.
	 */
	descriptionHtml: string | null,
};

/**
 *  The one write the board pane makes. Field-level and replayable, so a
 *  conflicting board never raises a banner (PLAN.md §5.3 step 5).
 */
export type CardOpDto = { kind: "add"; title: string; column: string | null; notes: string[]; position: PositionDto } | { kind: "retitle"; id: string; title: string } | 
/**  The empty string clears the description. */
{ kind: "setDescription"; id: string; description: string } | { kind: "move"; id: string; column: string | null; position: PositionDto } | { kind: "linkNote"; id: string; path: string } | { kind: "unlinkNote"; id: string; path: string } | { kind: "remove"; id: string } | 
/**
 *  To another board's first column, last, same id (ADR-0019); the source
 *  keeps a tombstone.
 */
{ kind: "moveToBoard"; id: string; board: string };

export type ColumnDto = {
	id: string,
	name: string,
};

/**  Which native context menu to pop at the pointer (ADR-0021, ADR-0032). */
export type ContextMenuDto = 
/**  A tree row; a board row gets "Show in Finder" only. */
{ kind: "tree"; board: boolean } | 
/**
 *  A card of the open board: its actions and the board's columns, the
 *  card's own one shown but not offered.
 */
{ kind: "card"; columns: ColumnDto[]; column: string; hasNote: boolean };

export type EditorSettingsDto = {
	fontSize: number,
};

/**
 *  One tree row. `path` is vault-relative and NFC; the root itself is `""`.
 * 
 *  `size` and `mtimeNs` are decimal strings, not numbers. A nanosecond
 *  timestamp is ~1.7e18 and a JS `number` is exact only to 2^53, and
 *  `specta-typescript` refuses to emit `u64`/`i64` at all. Strings round-trip
 *  exactly, which is what the save precondition depends on; the UI converts
 *  them once, for display.
 */
export type EntryDto = {
	path: string,
	name: string,
	dir: boolean,
	size: string,
	mtimeNs: string,
	cloudOnly: boolean,
	/**  Set when this directory holds a valid `board.json` (PLAN.md §5.5). */
	boardSlug: string | null,
	/**
	 *  The note this file looks like a vendor conflict copy *of*, when a
	 *  sibling by that name exists. Decided by `novalis_core`, so the tree and
	 *  `novalis doctor` agree — the UI used to re-implement a narrower regex
	 *  of its own and the two counts disagreed by construction.
	 */
	conflictCopyOf: string | null,
};

export type FileDto = {
	path: string,
	text: string,
	precondition: PreconditionDto,
	/**
	 *  False for a file that is not valid UTF-8: it opened read-only and its
	 *  text is lossy (PLAN.md §7.3).
	 */
	utf8: boolean,
	/**
	 *  A NUL byte in the first 8 KiB (ADR-0022): the body was never read,
	 *  `text` is empty, the precondition carries no hash, and the file opens
	 *  read-only.
	 */
	binary: boolean,
	/**  At or above 5 MB: no Markdown decorations, no highlighting. */
	plainMode: boolean,
	/**  At or above 50 MB: additionally warn. */
	huge: boolean,
};

/**  One debounce window's worth of changes. */
export type FsBatch = {
	added: EntryDto[],
	modified: EntryDto[],
	removed: string[],
	renamed: FsRename[],
};

/**  A stitched rename, both sides vault-relative. */
export type FsRename = {
	from: string,
	to: string,
};

/**
 *  A failed command. `code` is `CoreError::code()` for core failures, or one of
 *  the shell's own codes: `bad_request` (the UI sent something impossible),
 *  `no_vault` (no vault is open) and `internal`.
 */
export type IpcError = {
	/**  Catalog selector, e.g. `not_found`, `conflict`, `cloud_only`. */
	code: string,
	/**  Vault-relative path the failure is about, when there is one. */
	path: string | null,
	/**  Free text for `parse`/`io`/`internal`; never shown on its own. */
	detail: string | null,
	/**  `ambiguous` only: the note name that matched more than once. */
	name: string | null,
	/**  `ambiguous` only: the paths it matched. */
	candidates: string[],
};

export type LanguageDto = "system" | "de" | "en";

/**
 *  What the UI sees when a menu item is clicked. `id` is a `docs/KEYMAP.md`
 *  command id, or a `menu.`-prefixed id for the items that have no chord.
 */
export type MenuAction = {
	id: string,
};

/**
 *  One thing to open. The UI decides what it means: a file inside the open
 *  vault becomes a tab, anything else is said in a toast.
 */
export type OpenRequestDto = 
/**  An absolute file path. */
{ kind: "file"; path: string } | 
/**  A `novalis://` link, as it came. */
{ kind: "link"; url: string };

/**  Requests that arrived while the UI was running. */
export type OpenRequested = {
	items: OpenRequestDto[],
};

/**
 *  What a container (EPUB, CBZ — ADR-0023) gave back for one `read_packed`
 *  call: the table of contents when the call asked for no entry, otherwise
 *  the entries it asked for. One of the two is always empty.
 */
export type PackedDto = {
	path: string,
	entries: PackedEntryDto[],
	parts: PackedPartDto[],
};

/**  One row of a container's table of contents. */
export type PackedEntryDto = {
	/**
	 *  The entry's name inside the container, a relative path with forward
	 *  slashes. This is the name `read_packed` takes.
	 */
	name: string,
	/**  Uncompressed byte count as a decimal string (see `EntryDto`). */
	size: string,
};

/**  One entry's bytes, base64 for the same reason as `BlobDto`. */
export type PackedPartDto = {
	name: string,
	base64: string,
};

/**  Where a card goes inside its column. */
export type PositionDto = { kind: "first" } | { kind: "last" } | { kind: "after"; id: string };

/**
 *  The save precondition. Opaque to the UI: it is captured on open, handed
 *  back on save, and compared here. `mtimeNs` and `size` are decimal strings
 *  for the reason given on [`EntryDto`] — a lossy round-trip would turn every
 *  save into a false conflict.
 */
export type PreconditionDto = {
	mtimeNs: string,
	size: string,
	hash: string,
};

/**
 *  What `rename` did, including the link rewrite it triggered (PLAN.md §5.3
 *  step 2: the UI re-applies such a diff to a dirty buffer instead of raising
 *  the banner).
 */
export type RenameResultDto = {
	path: string,
	rewritten: string[],
	cardsUpdated: number,
	conflicts: string[],
	cloudOnlySkipped: string[],
};

/**
 *  One message on the search [`tauri::ipc::Channel`]. Hits stream in batches so
 *  a 10k-note vault does not post 10k messages at the UI thread.
 */
export type SearchEventDto = { kind: "hits"; hits: SearchHitDto[] } | { kind: "done"; report: SearchReportDto };

export type SearchHitDto = {
	path: string,
	line: number,
	snippet: string,
};

export type SearchQueryDto = {
	query: string,
	regex: boolean,
	caseSensitive: boolean,
	folder: string | null,
	/**
	 *  Only notes carrying this tag. Needs the cache; ignored while it is
	 *  still indexing.
	 */
	tag: string | null,
	limit: number | null,
	allFiles: boolean,
};

export type SearchReportDto = {
	scanned: number,
	cloudOnlySkipped: number,
	notUtf8Skipped: number,
	matches: number,
	truncated: boolean,
	/**  True when a newer search superseded this one before it finished. */
	cancelled: boolean,
};

export type SettingsDto = {
	version: number,
	language: LanguageDto,
	appearance: AppearanceDto,
	editor: EditorSettingsDto,
	spellcheck: boolean,
	lastVault: string | null,
};

/**
 *  A partial settings update. Absent fields stay as they are; there are only
 *  the four settings of PLAN.md §4.1 plus the `lastVault` state key, which the
 *  shell writes itself when a vault opens.
 */
export type SettingsPatchDto = {
	language: LanguageDto | null,
	appearance: AppearanceDto | null,
	fontSize: number | null,
	spellcheck: boolean | null,
};

/**  What `system_open` hands to macOS's opener (ADR-0021, ADR-0043). */
export type SystemOpenDto = 
/**  Show the file selected in the Finder (`open -R`). */
{ kind: "reveal"; path: string } | 
/**  Open it in the app macOS picks for its type (`open`). */
{ kind: "default"; path: string } | 
/**  A web or mail link, in the default browser or mail app (ADR-0044). */
{ kind: "url"; url: string };

export type TagCountDto = {
	tag: string,
	count: number,
};

export type TagListDto = {
	tags: TagCountDto[],
	/**
	 *  False while the first scan is still running, or if it failed. An empty
	 *  list then means "not known yet", not "none".
	 */
	indexed: boolean,
};

/**
 *  The two file orders of the tree: by name ascending (PLAN.md §4.2), or by
 *  modification time, newest first.
 */
export type TreeSortDto = "name" | "modified";

/**
 *  Everything that is persisted but is not a setting (PLAN.md §4.1): it lives
 *  in `<app-data>/state.json`, is disposable, and never appears in
 *  `docs/SETTINGS.md`.
 */
export type UiStateDto = {
	openTabs?: string[],
	activeTab?: string | null,
	sidebarVisible?: boolean,
	sidebarWidth?: number,
	boardVisible?: boolean,
	activeBoard?: string | null,
	/**
	 *  How the tree orders the files of a folder (ADR-0012). Folders are
	 *  always first and by name, whatever this says.
	 */
	treeSort?: TreeSortDto,
	backlinksVisible?: boolean,
	/**
	 *  The one-time cloud hint of PLAN.md §5.6 step 1 has been shown and
	 *  dismissed; state, not a setting (ADR-0004).
	 */
	cloudHintShown?: boolean,
	/**
	 *  The ten files most recently made current, newest first, for an empty
	 *  quick-open (ADR-0037); state, not a setting.
	 */
	recentFiles?: string[],
	/**
	 *  Set only on the UI's last save before quitting, once every open
	 *  buffer is on disk (D19): the shell writes the state and exits. Never
	 *  written to `state.json` (`state_save` drops the key).
	 */
	quit?: boolean,
	/**
	 *  Where the window was and how large (PLAN.md §4.1: state, not a
	 *  setting). The shell keeps it and fills it in on every save; the UI
	 *  never sets it.
	 */
	window?: WindowRectDto | null,
};

export type VaultDto = {
	/**  Absolute path, for the window title and the status bar only. */
	root: string,
	/**  Last path component, the name shown in the sidebar head. */
	name: string,
	kind: VaultKindDto,
	boards: BoardRefDto[],
	/**
	 *  Written by the old app and not migrated yet: its `.novalis/config.json`
	 *  is there and `vault.json` carries no `migrated` stamp (PLAN.md §10,
	 *  the read-only first-open prompt).
	 */
	legacy?: boolean,
};

export type VaultKindDto = "fileProvider" | "mirrored" | "local";

/**
 *  The result of opening a different vault: the same two fields `bootstrap`
 *  carries for one.
 */
export type VaultOpenDto = {
	vault: VaultDto,
	tree: EntryDto[],
};

/**
 *  The window's outer top-left corner and inner size, in physical pixels of
 *  the screen it was on.
 */
export type WindowRectDto = {
	x: number,
	y: number,
	width: number,
	height: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

