// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Everything the first paint needs, in one call (PLAN.md §2.3 rule 8).
	 *  The tree is the root listing only; sub-folders are fetched by `list_dir`
	 *  when they open, so first paint never waits for a walk (rule 1).
	 */
	bootstrap: () => typedError<BootstrapDto, IpcError>(__TAURI_INVOKE("bootstrap")),
	/**  The one dialog the app opens. Returns `None` when the user cancels. */
	openVaultDialog: () => typedError<string | null, IpcError>(__TAURI_INVOKE("open_vault_dialog")),
	openVault: (path: string) => typedError<VaultOpenDto, IpcError>(__TAURI_INVOKE("open_vault", { path })),
	listDir: (path: string) => typedError<EntryDto[], IpcError>(__TAURI_INVOKE("list_dir", { path })),
	/**
	 *  Every note in the vault, vault-relative and sorted.
	 * 
	 *  Quick-open (`Cmd+P`), the `[[`-completion source and the board's "Link
	 *  Note…" all need the whole list, and the tree only knows the folders the
	 *  user has opened. `walk_notes` runs under the materialize-off guard and
	 *  stats only, so a 10k-note cloud vault costs no downloads.
	 */
	listNotes: () => typedError<string[], IpcError>(__TAURI_INVOKE("list_notes")),
	readFile: (path: string) => typedError<FileDto, IpcError>(__TAURI_INVOKE("read_file", { path })),
	/**
	 *  Save. `expected` is the precondition captured when the buffer was loaded or
	 *  last written; a mismatch is a `conflict` and the target is left untouched,
	 *  so the UI can write the buffer to a conflict copy (§5.3 step 3).
	 */
	writeFile: (path: string, text: string, expected: {
	mtimeNs: string,
	size: string,
	hash: string,
} | null) => typedError<PreconditionDto, IpcError>(__TAURI_INVOKE("write_file", { path, text, expected })),
	/**
	 *  Write the buffer to `<name> (conflict <host> <YYYY-MM-DD HHMM>).<ext>` next
	 *  to the target and return the new vault-relative path. Never clobbers
	 *  (§5.3 step 3).
	 */
	writeConflictCopy: (path: string, text: string) => typedError<string, IpcError>(__TAURI_INVOKE("write_conflict_copy", { path, text })),
	createNote: (folder: string, name: string) => typedError<EntryDto, IpcError>(__TAURI_INVOKE("create_note", { folder, name })),
	createFolder: (folder: string, name: string) => typedError<EntryDto, IpcError>(__TAURI_INVOKE("create_folder", { folder, name })),
	/**
	 *  Rename or move, then rewrite the links that pointed at the old name.
	 * 
	 *  `vault::fs::rename` handles the case-only and normalization-only twins and
	 *  never clobbers; `relink_many` runs under the materialize-off guard and
	 *  writes each note under its read-time precondition, reporting what it had to
	 *  skip (§5.3 step 6).
	 */
	rename: (from: string, to: string) => typedError<RenameResultDto, IpcError>(__TAURI_INVOKE("rename", { from, to })),
	/**
	 *  Move to the Trash with `NsFileManager` (no prompt, no entitlement — the
	 *  §4.5 decision). A cloud-only file is refused rather than materialized.
	 */
	trash: (path: string) => typedError<null, IpcError>(__TAURI_INVOKE("trash", { path })),
	/**
	 *  Vault-wide search, streamed over a channel. A newer search supersedes an
	 *  older one: the running scan sees the generation change and stops, so there
	 *  is no cancel command and no way to leak a worker.
	 */
	search: (query: SearchQueryDto, onEvent: Channel<SearchEventDto>) => typedError<SearchReportDto, IpcError>(__TAURI_INVOKE("search", { query, onEvent })),
	/**
	 *  Every tag in the vault with its note count, most used first.
	 * 
	 *  Reads the cache on its own short-lived connection rather than through the
	 *  actor: the database is WAL and the actor's scan does its file reads before
	 *  it opens a write transaction, so a reader never waits on a scan.
	 */
	tags: () => typedError<TagListDto, IpcError>(__TAURI_INVOKE("tags")),
	/**  The notes and cards that link to `path` (§4.4, approved for v1). */
	backlinks: (path: string) => typedError<BacklinksDto, IpcError>(__TAURI_INVOKE("backlinks", { path })),
	boardList: () => typedError<BoardRefDto[], IpcError>(__TAURI_INVOKE("board_list")),
	/**
	 *  A board and its cards in one read. Tombstoned cards are dropped here;
	 *  cloud-only card files are reported, never read (§8.2).
	 */
	boardRead: (slug: string) => typedError<BoardDto, IpcError>(__TAURI_INVOKE("board_read", { slug })),
	/**
	 *  Create `boards/<slug>/board.json`. The board starts without columns: column
	 *  names are user text and the UI owns the catalog, so the shell never invents
	 *  one.
	 */
	boardCreate: (slug: string, name: string) => typedError<BoardRefDto, IpcError>(__TAURI_INVOKE("board_create", { slug, name })),
	/**
	 *  The two configurable things about a board: its name and its column list
	 *  (§8.5). Columns go through `set_columns`, which re-reads and replays on a
	 *  conflict, so two devices reordering columns never lose one.
	 */
	boardWrite: (slug: string, name: string | null, columns: ColumnDto[] | null) => typedError<BoardDto, IpcError>(__TAURI_INVOKE("board_write", { slug, name, columns })),
	/**
	 *  The one write the board pane makes. Every variant is a single replayable
	 *  field change, which is why a conflicting board never raises a banner
	 *  (§5.3 step 5).
	 */
	cardWrite: (slug: string, op: CardOpDto) => typedError<CardDto, IpcError>(__TAURI_INVOKE("card_write", { slug, op })),
	/**
	 *  Change one or more of the four settings (PLAN.md §4.1). Writes
	 *  `settings.json` atomically and rebuilds the native menu so its check marks
	 *  and the Language/Appearance submenus match.
	 */
	settingsSet: (patch: SettingsPatchDto) => typedError<SettingsDto, IpcError>(__TAURI_INVOKE("settings_set", { patch })),
	/**
	 *  Persist the disposable half of the UI state (open tabs, sidebar, board).
	 *  It lives in `<app-data>/state.json` and is deliberately not documented in
	 *  `docs/SETTINGS.md` (PLAN.md §4.1).
	 */
	stateSave: (uiState: UiStateDto) => typedError<null, IpcError>(__TAURI_INVOKE("state_save", { uiState })),
};

/** Events */
export const events = {
	cacheUpdated: makeEvent<CacheUpdated>("cache-updated"),
	fsBatch: makeEvent<FsBatch>("fs-batch"),
	menuAction: makeEvent<MenuAction>("menu-action"),
};

/* Types */
export type AppearanceDto = "system" | "light" | "dark";

export type BacklinkDto = {
	path: string,
	title: string,
	/**  The line the link sits on, 1-based. */
	line: number,
};

export type BacklinksDto = {
	notes: BacklinkDto[],
	/**  See [`TagListDto::indexed`]. */
	indexed: boolean,
};

/**  A board with its cards, in one read. Tombstoned cards are not sent. */
export type BoardDto = {
	slug: string,
	name: string,
	columns: ColumnDto[],
	cards: CardDto[],
	/**  Card files that are online only and were therefore never read. */
	cloudOnly: string[],
	/**
	 *  Cards whose `column` is not in `columns` any more; the UI shows them in
	 *  the first column with a marker (`board.columnMissing`).
	 */
	orphanCards: string[],
};

export type BoardRefDto = {
	slug: string,
	name: string,
};

export type BootstrapDto = {
	settings: SettingsDto,
	vault: VaultDto | null,
	/**
	 *  The vault root's children. Sub-folders are fetched lazily by `list_dir`,
	 *  so the first paint never waits for a full walk (PLAN.md §2.3 rule 1).
	 */
	tree: EntryDto[],
	lastOpen: UiStateDto,
	/**
	 *  The resolved UI language (`de` or `en`) — `language: system` is
	 *  resolved here so the UI and the native menu agree.
	 */
	locale: string,
};

/**
 *  Emitted after every completed scan, so the panels that read the cache
 *  refetch when there is something new rather than on a timer (§2.3 rule 12
 *  forbids polling).
 */
export type CacheUpdated = {
	/**
	 *  False when the cache could not be opened or scanned; the tag filter and
	 *  the backlinks list then say so instead of showing an empty result.
	 */
	indexed: boolean,
};

export type CardDto = {
	id: string,
	title: string,
	column: string,
	order: string,
	notes: string[],
	created: string,
	updated: string,
};

/**
 *  The one write the board pane makes. Field-level and replayable, so a
 *  conflicting board never raises a banner (PLAN.md §5.3 step 5).
 */
export type CardOpDto = { kind: "add"; title: string; column: string | null; notes: string[]; position: PositionDto } | { kind: "retitle"; id: string; title: string } | { kind: "move"; id: string; column: string | null; position: PositionDto } | { kind: "linkNote"; id: string; path: string } | { kind: "unlinkNote"; id: string; path: string } | { kind: "remove"; id: string };

export type ColumnDto = {
	id: string,
	name: string,
};

export type EditorSettingsDto = {
	fontSize: number,
};

/**
 *  One tree row. `path` is vault-relative and NFC; the root itself is `""`.
 * 
 *  `size` and `mtimeNs` are decimal strings, not numbers. A nanosecond
 *  timestamp is ~1.7e18 and a JS `number` is exact only to 2^53, and
 *  `specta-typescript` refuses to emit `u64`/`i64` at all. Strings round-trip
 *  exactly, which is what the save precondition depends on; the UI converts
 *  them once, for display.
 */
export type EntryDto = {
	path: string,
	name: string,
	dir: boolean,
	size: string,
	mtimeNs: string,
	cloudOnly: boolean,
	/**  Set when this directory holds a valid `board.json` (PLAN.md §5.5). */
	boardSlug: string | null,
};

export type FileDto = {
	path: string,
	text: string,
	precondition: PreconditionDto,
	/**
	 *  False for a file that is not valid UTF-8: it opened read-only and its
	 *  text is lossy (PLAN.md §7.3).
	 */
	utf8: boolean,
	/**  At or above 5 MB: no Markdown decorations, no highlighting. */
	plainMode: boolean,
	/**  At or above 50 MB: additionally warn. */
	huge: boolean,
};

/**  One debounce window's worth of changes. */
export type FsBatch = {
	added: EntryDto[],
	modified: EntryDto[],
	removed: string[],
	renamed: FsRename[],
};

/**  A stitched rename, both sides vault-relative. */
export type FsRename = {
	from: string,
	to: string,
};

/**
 *  A failed command. `code` is `CoreError::code()` for core failures, or one of
 *  the shell's own codes: `bad_request` (the UI sent something impossible),
 *  `no_vault` (no vault is open) and `internal`.
 */
export type IpcError = {
	/**  Catalog selector, e.g. `not_found`, `conflict`, `cloud_only`. */
	code: string,
	/**  Vault-relative path the failure is about, when there is one. */
	path: string | null,
	/**  Free text for `parse`/`io`/`internal`; never shown on its own. */
	detail: string | null,
	/**  `ambiguous` only: the note name that matched more than once. */
	name: string | null,
	/**  `ambiguous` only: the paths it matched. */
	candidates: string[],
};

export type LanguageDto = "system" | "de" | "en";

/**
 *  What the UI sees when a menu item is clicked. `id` is a `docs/KEYMAP.md`
 *  command id, or a `menu.`-prefixed id for the items that have no chord.
 */
export type MenuAction = {
	id: string,
};

/**  Where a card goes inside its column. */
export type PositionDto = { kind: "first" } | { kind: "last" } | { kind: "after"; id: string };

/**
 *  The save precondition. Opaque to the UI: it is captured on open, handed
 *  back on save, and compared here. `mtimeNs` and `size` are decimal strings
 *  for the reason given on [`EntryDto`] — a lossy round-trip would turn every
 *  save into a false conflict.
 */
export type PreconditionDto = {
	mtimeNs: string,
	size: string,
	hash: string,
};

/**
 *  What `rename` did, including the link rewrite it triggered (PLAN.md §5.3
 *  step 2: the UI re-applies such a diff to a dirty buffer instead of raising
 *  the banner).
 */
export type RenameResultDto = {
	path: string,
	rewritten: string[],
	cardsUpdated: number,
	conflicts: string[],
	cloudOnlySkipped: string[],
};

/**
 *  One message on the search [`tauri::ipc::Channel`]. Hits stream in batches so
 *  a 10k-note vault does not post 10k messages at the UI thread.
 */
export type SearchEventDto = { kind: "hits"; hits: SearchHitDto[] } | { kind: "done"; report: SearchReportDto };

export type SearchHitDto = {
	path: string,
	line: number,
	snippet: string,
};

export type SearchQueryDto = {
	query: string,
	regex: boolean,
	caseSensitive: boolean,
	folder: string | null,
	/**
	 *  Only notes carrying this tag. Needs the cache; ignored while it is
	 *  still indexing.
	 */
	tag: string | null,
	limit: number | null,
	allFiles: boolean,
};

export type SearchReportDto = {
	scanned: number,
	cloudOnlySkipped: number,
	notUtf8Skipped: number,
	matches: number,
	truncated: boolean,
	/**  True when a newer search superseded this one before it finished. */
	cancelled: boolean,
};

export type SettingsDto = {
	version: number,
	language: LanguageDto,
	appearance: AppearanceDto,
	editor: EditorSettingsDto,
	spellcheck: boolean,
	lastVault: string | null,
};

/**
 *  A partial settings update. Absent fields stay as they are; there are only
 *  the four settings of PLAN.md §4.1 plus the `lastVault` state key, which the
 *  shell writes itself when a vault opens.
 */
export type SettingsPatchDto = {
	language: LanguageDto | null,
	appearance: AppearanceDto | null,
	fontSize: number | null,
	spellcheck: boolean | null,
};

export type TagCountDto = {
	tag: string,
	count: number,
};

export type TagListDto = {
	tags: TagCountDto[],
	/**
	 *  False while the first scan is still running, or if it failed. An empty
	 *  list then means "not known yet", not "none".
	 */
	indexed: boolean,
};

/**
 *  Everything that is persisted but is not a setting (PLAN.md §4.1): it lives
 *  in `<app-data>/state.json`, is disposable, and never appears in
 *  `docs/SETTINGS.md`.
 */
export type UiStateDto = {
	openTabs?: string[],
	activeTab?: string | null,
	sidebarVisible?: boolean,
	sidebarWidth?: number,
	boardVisible?: boolean,
	activeBoard?: string | null,
};

export type VaultDto = {
	/**  Absolute path, for the window title and the status bar only. */
	root: string,
	/**  Last path component, the name shown in the sidebar head. */
	name: string,
	kind: VaultKindDto,
	boards: BoardRefDto[],
};

export type VaultKindDto = "fileProvider" | "mirrored" | "local";

/**
 *  The result of opening a different vault: the same two fields `bootstrap`
 *  carries for one.
 */
export type VaultOpenDto = {
	vault: VaultDto,
	tree: EntryDto[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

